### ISSUE TITLE
Select multiple keys

### ISSUE THREAD

**Issue by wahidibrahimy** [auditassistant/json-query#35]
var jsonQuery = require("json-query")

var data= {
"jobRequisitions": [
    {
      "itemID": "JR1234567899",
      "clientRequisitionID": "ADPRM-1234567899",
      "requisitionDescription": "A major company has an immediate opening for an enthusiastic and detailed oriented sales account manager",
      "requisitionStatusCode": {
        "effectiveDate": "2014-01-01",
        "codeValue": "O",
        "shortName": "Open"
      }
      },
      {
      "itemID": "JR1234567890",
      "clientRequisitionID": "ADPRM-1234567890",
      "requisitionDescription": "A major company has an immediate opening for an enthusiastic and detailed oriented sales account manager",
      "requisitionStatusCode": {
        "effectiveDate": "2014-01-01",
        "codeValue": "O",
        "shortName": "Open"
      }
      }
     ]
}

jsonQuery('jobRequisitions:select(**itemID, requisitionStatusCode.effectiveDate**)', {
  data: data,
  locals: {
    select: function (input) {
      if (Array.isArray(input)) {
        var keys = [].slice.call(arguments, 1)
        return input.map(function (item) {
          return Object.keys(item).reduce(function (result, key) {
            if (~keys.indexOf(key)) {
              result[key] = item[key]
            }
            return result
          }, {})
        })
      }
    }
  }
})

**Comment by mmckegg** [comment]
Sorry, I don't understand the question. Do you want to change this code to select more than one key?
